name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Gera uma animação de snake a partir do gráfico de contribuições do usuário no GitHub, e salva o resultado em um arquivo svg
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          color_snake: dark
          color_dots: "#3f3f3f,#ffffff,#8b949e,#e4e2e2"

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
